//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIPER Swift Xcode Templates
//
import UIKit

class ___FILEBASENAMEASIDENTIFIER___Routing: RoutingProtocolBase {
    weak var viewController:___FILEBASENAMEASIDENTIFIER___ViewController!
    weak var presenter: ___FILEBASENAMEASIDENTIFIER___Presenter!
    weak var interactor: ___FILEBASENAMEASIDENTIFIER___Interactor!
    required init() {
       
    }
    
    func loadView() -> ___FILEBASENAMEASIDENTIFIER___ViewController{
        
        let storyBoard = UIStoryboard.___FILEBASENAMEASIDENTIFIER___Storyboard()
        let viewController = storyBoard.instantiateViewController(withIdentifier:"___FILEBASENAMEASIDENTIFIER___SceneView") as! ___FILEBASENAMEASIDENTIFIER___ViewController
        return viewController
    }
}

extension UIStoryboard {
    static func ___FILEBASENAMEASIDENTIFIER___Storyboard() -> UIStoryboard {
        return self.init(name: "___FILEBASENAMEASIDENTIFIER___", bundle: Bundle.main)
    }
    
}