//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIPER Swift Xcode Templates
//

import UIKit

class ___FILEBASENAMEASIDENTIFIER___ViewController: UIViewController, ViewControllerProtocolBase {
    typealias PresenterType = ___FILEBASENAMEASIDENTIFIER___PresenterProtocolView
    
    var presenter:___FILEBASENAMEASIDENTIFIER___PresenterProtocolView!
    
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }    
}

extension ___FILEBASENAMEASIDENTIFIER___ViewController: ___FILEBASENAMEASIDENTIFIER___ViewProtocolPresenter {
    
}

