//  ViperInteractor.swift
//  ViperExample
//  Created by Alejo on 12/7/16.
//  Copyright © 2016 gapps. All rights reserved.
//  This file was generated by the VIPER Swift Xcode Templates
class ViperInteractor:ViperInteractorProtocolPresenter, InteractorProtocolBase{
    typealias PresenterType = ViperPresenterProtocolInteractor
    weak var presenter:ViperPresenterProtocolInteractor?
    required init() {
    }
    func loadData() {
        ///LOAD DATA FROM INTERNET OR DATABASE
        print("LOAD DATA AND THEN CALL THE PRESENTER TO SET DATA")
        presenter?.setData()
    }
}
