//  ViperPresenterProtocol.swift
//  ViperExample
//  Created by Alejo on 12/7/16.
//  Copyright © 2016 gapps. All rights reserved.
//  This file was generated by the VIPER Swift Xcode Templates
protocol ViperPresenterProtocolView: PresenterProtocolViewBase {
    func loadData()
}
protocol ViperPresenterProtocolInteractor: PresenterProtocolInteractorBase {
    func setData()
}
