//
//  ViperRouter.swift
//  ViperExample
//
//  Created by Alejo on 12/7/16.
//  Copyright © 2016 gapps. All rights reserved.
//
//  This file was generated by the VIPER Swift Xcode Templates
//
import UIKit

class ViperRouting: RoutingProtocolBase {
    weak var viewController:ViperViewController!
    weak var presenter: ViperPresenter!
    weak var interactor: ViperInteractor!
    required init() {
       
    }
    
    func loadView() -> ViperViewController{
        
        let storyBoard = UIStoryboard.ViperStoryboard()
        let viewController = storyBoard.instantiateViewController(withIdentifier:"ViperSceneView") as! ViperViewController
        return viewController
    }
}

extension UIStoryboard {
    static func ViperStoryboard() -> UIStoryboard {
        return self.init(name: "Viper", bundle: Bundle.main)
    }
    
}