//
//  ViperPresenter.swift
//  ViperExample
//
//  Created by Alejo on 12/7/16.
//  Copyright © 2016 gapps. All rights reserved.
//
//  This file was generated by the VIPER Swift Xcode Templates
//


class ViperPresenter:ViperPresenterProtocolView,ViperPresenterProtocolInteractor,PresenterProtocolBase {
    typealias ViewControllerType = ViperViewProtocolPresenter
    typealias RoutingType = ViperRouting
    
    weak var viewController:ViewControllerType?
    var interactor:ViperInteractorProtocolPresenter!
    var routing:RoutingType!

    required init() {
        // init of presenter
    }
    
    
    func loadData() {
        //LOGIC BUSSINESS
        print("LOGIC BUSSINESS AND PRESENTER CALL INTERACTOR")
        interactor.loadData()
    
    }
    
    func setData() {
        
        print("PRESENTER CALL THE VIEW TO SET DATA")
        viewController?.setData()
    }
    
    
    
    
}
